language: php
matrix:
  include:
    - php: 7.2
sudo: false
before_install:
  - export NEOS_TARGET_VERSION=5.0
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git -b ${NEOS_TARGET_VERSION}
  - cd neos-base-distribution
  - composer require --no-update --no-interaction neos/metadata-extractor
install:
  - composer install --no-interaction
  - cd ..
  - rm -rf neos-base-distribution/Packages/Application/Neos.MetaData.Extractor
  - mv metadata-extractor neos-base-distribution/Packages/Application/Neos.MetaData.Extractor
  - cd neos-base-distribution
script:
  - bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Neos.MetaData.Extractor/Tests/Unit
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Neos.MetaData.Extractor/Tests/Functional
